name:                cipher-cli
version:             0.0.0.1
github:              "Vincibean/cipher-cli"
license:             GPL-3
author:              "Vincibean"
maintainer:          "sepensi@gmail.com"
copyright:           "2020 Vincibean"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/cipher-cli#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cipher-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cipher-cli
    - cmdargs

tests:
  cipher-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cipher-cli
    - hspec
    - QuickCheck
